### PR TITLE
Creating tests for the horse.

### PR DESCRIPTION
**Pull request by GlerystonMatos**
Creation of the DUnitX project group (horse \ tests \ src \ DUnitX.groupproj)

Within the project group there are two projects, one to test the horse console and the other to test the horse vcl.

Both share the same tests, being separate projects just to be able to use the different build directives.

The executables are generated in the folder (horse \ tests), they were versioned so they can be used in the action tests, created on github.

The created action will execute the tests at each commit and will notify the success or failure through the badge created in the readme in the new tests section.

In the same section, two more badges were created, to inform the coverage of the tests in the console and vcl project.

To generate the code coverage report, code coverage was used, to generate the coverage reports just use the .bats in the folder (horse \ tests \ code-coverage)

Currently the coverage is 39% for the console and 38% for the VCL.

I didn't invest a lot in creating tests because I wanted to validate the structure created for the execution, the same being approved, we can invest in writing tests.

### CODE REVIEW

**Review by CarlosHe — COMMENTED** [review]
I would just change the name of the variables, to keep it more standard with the Delphi and Horse declarations!

example:
- starting with the letter L for 'local' var. (internal var to the method)
- starting with the letter F for 'field' var. (internal var to the class)
- starting with the letter A for 'attribute' var. (name of method attributes - functions and procedures)

**Comment by GlerystonMatos** [comment]
> I would just change the name of the variables, to keep it more standard with the Delphi and Horse declarations!
> 
> example:
> 
> * starting with the letter L for 'local' var. (internal var to the method)
> * starting with the letter F for 'field' var. (internal var to the class)
> * starting with the letter A for 'attribute' var. (name of method attributes - functions and procedures)

I will make the adjustments to leave the default

**Comment by CarlosHe** [comment]
Could you change the messages and variable names to English? I believe this is the last change requested to accept the Pull Resquest.

**Comment by GlerystonMatos** [comment]
> Could you change the messages and variable names to English? I believe this is the last change requested to accept the Pull Resquest.

I will make the change

**Pull request merged**
